import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/app/navbar";
import Navbar from "@/app/navbarMobile";
import Footer from "@/components/Footer";

const JakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={JakartaSans.className}>
        <main>
          <Header />
          {children}
          <Navbar />
          <Footer />
        </main>
      </body>
    </html>
  );
}
